### ISSUE TITLE
Transparent profile dropdown

### ISSUE THREAD

**Issue by ujjwalt** [tailwindlabs/tailwindui-issues#426]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/multi-column
- Component name: Constrained three column

**Describe the bug**
The profile dropdown is transparent and shows the the third column behind it translucently.

**Expected behavior**
The profile dropdown menu is expected to have a white background that overlays on top of the third column

**Screenshots**
<img width="371" alt="Screenshot 2021-01-04 at 4 21 37 PM" src="https://user-images.githubusercontent.com/660290/103527909-12654b80-4ea9-11eb-87f3-60bc420f46b7.png">

**Browser/Device (if applicable)**
 - OS: MacOS Big Sur 11.1
 - Browser: Chrome
 - Version: 87.0.4280.88

**Comment by davidluhr** [comment]
@ujjwalt Great catch! Looks like it needed `z-10` to prevent other `absolute` elements from sitting above it. I've fixed this and it should be live on the site soon. Thanks for reporting this.

**Comment by cweitat** [comment]
Issue still happens in the examples given in https://tailwindui.com/components/application-ui/navigation/navbars
`z-10` needed to update manually still as of so far
